version: "3.1"
services:
    mariadb:
      image: mariadb:latest
      container_name: esgi-school-mariadb
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=esgi
        - MYSQL_USER=esgi
        - MYSQL_PASSWORD=esgi
      ports:
        - "8003:3306"

    webserver:
      image: nginx:stable
      container_name: esgi-school-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./engine/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8000:80"

    php-fpm:
      build: engine/php-fpm
      container_name: esgi-school-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./engine/php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini

    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      links:
        - mariadb:db
      ports:
        - 8004:80
      environment:
        MYSQL_USERNAME: root
        MYSQL_ROOT_PASSWORD: root