front:
    image: nginx
    ports:
        - "8082:80"
    links:
        - "engine:engine"
    volumes:
        - "./sources:/home/docker:rw"
        - "./docker/front/default.conf:/etc/nginx/conf.d/default.conf:ro"
engine:
    build: ./docker/engine/
    volumes:
        - "./sources:/home/docker:rw"
        - "./docker/engine/php.ini:/usr/local/etc/php/conf.d/custom.ini:ro"
    links:
        - "db:db"
    working_dir: "/home/docker"
db:
    image: mariadb:latest
    ports:
        - "3306:3306"
    environment:
        - "MYSQL_ROOT_PASSWORD=root"
        - "MYSQL_USER=esgi"
        - "MYSQL_PASSWORD=esgi"
        - "MYSQL_DATABASE=esgi"
phpmyadmin:
  image: phpmyadmin/phpmyadmin
  links:
    - db:db
  ports:
    - 8088:80
  environment:
    MYSQL_USERNAME: root
    MYSQL_ROOT_PASSWORD: root
